database:
  host: "user_db"
  user: "daffaputra"
  password: "password"
  port: "5432"
  name: "dropboks"
  sslmode: "disable"

app:
  name: "dropboks"
  url: "http://localhost/api/v1"
  http:
    port: 80
  grpc:
    port: 50051
    service:
      file_service: file_service:50051
  verification_url: "verify-email?"
  auth_url: "http://localhost/api/v1"
  
redis:
  address: "redis"
  port: "6379"
  client_name: "auth_service"
  password: "this_is_password"

nats:
  protocol: "nats"
  address: "nats"
  port: "4221"
  credential:
    user: "mq_user"
    password: "strong_password123"
  connection_name: "user_service_conn"
  timeout: 10

jetstream:
  notification:
    stream: 
      name: "notification_stream"
      description: "this is notification stream"
    subject:
      global: "notification.>"
      mail: "notification.email"
  event:
    stream: 
      name: "event_stream"
      description: "this is event bus stream"
    subject:
      global: "event.>"
      event_bus: "event"

server:
  cors:
    allow_origins: "*"
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    allow_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-Token, Accept, Origin, Cache-Control, X-File-Name, X-File-Type, X-File-Size"
    expose_headers: "Content-Length, Content-Range"
    max_age: 86400
    allow_credential: true
