database:
  host: "localhost"
  user: "daffaputra"
  password: "password"
  port: "5432"
  name: "dropboks"
  sslmode: "disable"

app:
  name: "dropboks"
  url: "http://localhost:8082"
  grpc:
    port: 50051
    service:
      file_service: 127.0.0.1:50052
  http:
    port: 8082
  verification_url: "verify-email?"
  auth_url: "http://localhost:8181"

redis:
  address: "localhost"
  port: "6379"
  client_name: "auth_service"
  password: "this_is_password"

nats:
  protocol: "nats"
  address: "localhost"
  port: "4221"
  credential:
    user: "mq_user"
    password: "strong_password123"
  connection_name: "user_service_conn"
  timeout: 10

jetstream:
  notification:
    stream:
      name: "notification_stream"
      description: "this is notification stream"
    subject:
      global: "notification.>"
      mail: "notification.email"
  event:
    stream:
      name: "eventbus_stream"
      description: "this is event bus stream"
    subject:
      global: "eventbus.>"
      event_bus: "eventbus"
  log:
    stream:
      name: "log_stream"
      description: "this is log stream"
    subject:
      global: "log.>"
      prefix: "log"

server:
  cors:
    allow_origins: "*"
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    allow_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-Token, Accept, Origin, Cache-Control, X-File-Name, X-File-Type, X-File-Size"
    expose_headers: "Content-Length, Content-Range"
    max_age: 86400
    allow_credential: true
