database:
  host: "test_user_db"
  user: "user_test"
  password: "password_test"
  port: "5432"
  name: "testdb"
  sslmode: "disable"

app:
  name: "test_app_name"
  url: "http://localhost:9090/api/v1"
  http:
    port: 80
  grpc:
    port: 50051
    service:
      file_service: test_file_service:50051
  verification_url: "auth/verify-email?"
  auth_url: "http://localhost:9090/api/v1"

minio:
  host: "test_minio"
  port: "9000"
  credential:
    user: "user_test"
    password: "password_test"

redis:
  address: "test_redis"
  port: "6379"
  client_name: "auth_service_test"
  password: "password_test"

nats:
  protocol: "nats"
  address: "test_nats"
  port: "4221"
  credential:
    user: "user_test"
    password: "password_test"
  connection_name: "user_service_conn_test"
  timeout: 10

jetstream:
  notification:
    stream:
      name: "notification_stream_test"
      description: "this is notification stream"
    subject:
      global: "test_notif.>"
      mail: "test_notif.email"
  event:
    stream:
      name: "event_stream_test"
      description: "this is event bus stream"
    subject:
      global: "test_event.>"
      event_bus: "test_event"
  log:
    stream:
      name: "log_stream"
      description: "this is log stream"
    subject:
      global: "log.>"
      prefix: "log"

server:
  cors:
    allow_origins: "*"
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    allow_headers: "Content-Type, Authorization, X-Requested-With, X-CSRF-Token, Accept, Origin, Cache-Control, X-File-Name, X-File-Type, X-File-Size"
    expose_headers: "Content-Length, Content-Range"
    max_age: 86400
    allow_credential: true
jwt:
  secret_key: "jwt_secret_test"

container:
  auth_service_version: "latest"
  file_service_version: "latest"
  user_service_version: "test"
  notification_service_version: "latest"
  gateway_version: "1.28.0-alpine-slim"
  nats_version: "2.11.6"
  minio_version: "RELEASE.2025-05-24T17-08-30Z-cpuv1"
  mailhog_version: "v1.0.1"
  postgresql_version: "17.5-alpine3.22"
  redis_version: "7.2"

script:
  nats_server: "../mocks/nats/nats-server.conf"
  init_sql: "../mocks/db/init-db.sql"
  nginx: "../mocks/gateway/nginx.conf"
  grpc_error: "../mocks/gateway/errors.grpc_conf"
